import Head from 'next/head'
import Image from 'next/image'
import Login from '../components/Login'
import UserDashboard from '../components/UserDashboard'
//import BasicTable from '../components/Table'
import { useAuth } from '../context/AuthContext'
import useFetchPeople from '../hooks/fetchPeople'

export default function Home() {
  const { currentUser } = useAuth();
  const { people, setPeople, loading, error } = useFetchPeople(); 

  console.log(people);
  console.log(error);
  return (
    < >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!currentUser && <Login />}
      {currentUser && <UserDashboard/>}
    </>
  )
}
